name: Verfy Activation
on:
    workflow_dispatch: {}
jobs:
    activation:
        name: Verfy activation
        runs-on: ubuntu-latest
        steps:
            - name: Unity - Activate
              uses: game-ci/unity-activate@v2.0.0
